name: Build and Publish Images

on:
  schedule:
    - cron: "0 3 * * *" # Run every day at 3am
  push:
    branches:
      - main

jobs:
  # base:
  #   name: Build and Publish Base Image
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker
  #       uses: docker/setup-buildx-action@v3

  #     - name: Log into GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./images/base
  #         platforms: linux/amd64,linux/arm64
  #         cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:buildcache
  #         cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:buildcache
  #         tags: ghcr.io/${{ github.repository_owner }}/base:latest
  #         push: true

  runner:
    name: Build and Publish Runner Image
    runs-on: ubuntu-latest
    # needs: [base]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/runner
          platforms: linux/amd64,linux/arm64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/runner:buildcache
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/runner:buildcache
          tags: ghcr.io/${{ github.repository_owner }}/runner:latest
          push: true
