name: Publish Docker Images

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main

jobs:
  base-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./base-image
          push: true
          tags: |
            ghcr.io/onezerocompany/base:latest
            ghcr.io/onezerocompany/base:${{ github.sha }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386,linux/ppc64le,linux/s390x
          cache-from: type=registry,ref=ghcr.io/onezerocompany/base:cache
          cache-to: type=registry,ref=ghcr.io/onezerocompany/base:cache

  devcontainer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./devcontainer-image
          push: true
          tags: |
            ghcr.io/onezerocompany/devcontainer:latest
            ghcr.io/onezerocompany/devcontainer:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/onezerocompany/devcontainer:cache
          cache-to: type=registry,ref=ghcr.io/onezerocompany/devcontainer:cache
