name: Publish Docker Images

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main

jobs:
  base-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Image
        uses: ./.github/actions/build-image
        with:
          name: base
          folder: ./base-image

  runner:
    runs-on: ubuntu-latest
    needs: base-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Image
        uses: ./../actions/build-image
        with:
          name: runner
          folder: ./runner-image

  devcontainer:
    runs-on: ubuntu-latest
    needs: base-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Image
        uses: ./../actions/build-image
        with:
          name: devcontainer
          folder: ./devcontainer-image
