name: Build and Publish Images & Features

on:
  schedule:
    - cron: "0 3 * * *" # Run every day at 3am
  push:
    branches:
      - main

jobs:
  base:
    name: Build and Publish Base Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/base
          platforms: linux/amd64,linux/arm64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:buildcache
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:buildcache
          tags: ghcr.io/${{ github.repository_owner }}/base:latest
          push: true

  runner:
    name: Build and Publish Runner Image
    runs-on: ubuntu-latest
    needs: [base]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/runner
          platforms: linux/amd64,linux/arm64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/runner:buildcache
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/runner:buildcache
          tags: ghcr.io/${{ github.repository_owner }}/runner:latest
          push: true

  features:
    name: Build and Publish Features
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./features/src"
          disable-repo-tagging: "true"
          features-namespace: "onezerocompany/devcontainers/features"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  devcontainers:
    name: Build and Publish Devcontainers
    runs-on: ubuntu-latest
    needs: [features, base]
    strategy:
      matrix:
        devcontainer: [universal, minimal]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Devcontainer
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          subFolder: devcontainers/${{ matrix.devcontainer }}
          imageName: ghcr.io/${{ github.repository_owner }}/devcontainer/${{ matrix.devcontainer }}
          cacheFrom: ghcr.io/${{ github.repository_owner }}/devcontainer/${{ matrix.devcontainer }}
          push: filter
          refFilterForPush: refs/heads/main
          platform: linux/amd64,linux/arm64
          imageTag: latest
