name: Test Build Images

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test Build Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        devcontainer:
          [
            { id: flutter, platforms: "linux/amd64" },
            { id: astro, platforms: "linux/amd64,linux/arm64" },
            { id: minimal, platforms: "linux/amd64,linux/arm64" },
            { id: containers, platforms: "linux/amd64,linux/arm64" },
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Devcontainer
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          subFolder: devcontainers/${{ matrix.devcontainer.id }}
          imageName: ghcr.io/${{ github.repository_owner }}/devcontainer/${{ matrix.devcontainer.id }}
          push: false
          platform: ${{ matrix.devcontainer.platforms }}
          imageTag: latest
